include: package:flutter_lints/flutter.yaml

plugins:
  my_lints:
    path: ../../Dart/my_lints

linter:
  rules:
    avoid_print: false
    no_literal_bool_comparisons: true
    prefer_null_aware_operators: true
    unnecessary_null_checks: true
